name: HEXO_DEPLOY_TENCENT

on:
  push:
    branches:
      - source

jobs:
  build:
    name: deploy-tencent
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest]
        node_version: [16.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Checkout Secrets
        run: echo "${{secrets.SECRETID}}"
        run: echo "${{secrets.SECRETKEY}}"
        run: echo "${{secrets.ENV_ID}}"

      - name: Deploy static to Tencent CloudBase
        uses: TencentCloudBase/cloudbase-action@v2 
        with:
          secretId: ${{secrets.SECRETID}}
          secretKey: ${{secrets.SECRETKEY}}
          envId: ${{secrets.ENV_ID}}
